apiVersion: v1
kind: Service
metadata:
  name: {{ include "pilosa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pilosa.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: pilosa
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "pilosa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
