apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pilosa-cluster.fullname" . }}
  labels:
    {{ include "pilosa-cluster.labels" . | indent 4 }}
data:
  coordinator.toml: |
    # Configuration for the Pilosa coordinator node.
    bind = "{{pilosa.coordinator}}:10101"
    [cluster]
    coordinator = true
  node.toml: |
    # Configuration for Pilosa non-coordinator nodes.
    bind = "0.0.0.0:10101"
    [gossip]
    seeds = ["{{pilosa.coordinator}}:15000"]
